name: C

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: running code
      uses: ./.github/testactions/code.c
      run: gcc code.c -o code; ./code
