name: testing c

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: running code
      run: gcc lauratorralba/testactions/code.c -o code; ./code
