name: C

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: firs step
      uses: ./testactions/code.c
    - name: second
      run: gcc code.c -o code; ./code
